export enum Tag {
  CENSORSHIP_RESISTANCE = 'censorship-resistance',
  CONSENSUS_INCENTIVES = 'consensus-incentives',
  DATA_AVAILABILITY = 'data-availability',
  FRAUD_PROOFS = 'fraud-proofs',
  INCLUSION_LISTS = 'inclusion-lists',
  LAYER_2 = 'layer-2',
  MEV = 'mev',
  P2P = 'p2p',
  POST_QUANTUM = 'post-quantum',
  PRECONFIRMATIONS = 'preconfirmations',
  PROPOSER_BUILDER_SEPARATION = 'proposer-builder-separation',
  ROLLUP = 'rollup',
  SCALING = 'scaling',
  SIGNATURE_AGGREGATION = 'signature-aggregation',
  SINGLE_SLOT_FINALITY = 'single-slot-finality',
  STATELESS = 'stateless',
  SYBIL_ATTACK = 'sybil-attack',
  VALIDATOR_CONSOLIDATION = 'validator-consolidation',
} 